### ISSUE TITLE
crashing with TIME-OUT at node-red startup

### ISSUE THREAD

**Issue by fcichos** [urbiworx/node-red-contrib-hue#4]
Hi,

I have the hue nodes running on my pi and recently they started to crash node-red at startup even when I don't have any hue set or so included in my flows. So I guess it crashes when its registered.
The messages are 

23 Aug 09:50:16 - [info] Settings file  : /usr/local/lib/node_modules/node-red/settings.js
23 Aug 09:50:16 - [info] User directory : /home/pi/.node-red
23 Aug 09:50:16 - [info] Flows file : /home/pi/.node-red/flows_pifra.json
23 Aug 09:50:16 - [info] Server now running at http://127.0.0.1:1880/
23 Aug 09:50:16 - [info] Starting flows
23 Aug 09:50:17 - [info] [inject:bae81d2d.4517e] repeat = 60000
23 Aug 09:50:17 - [info] [inject:getTime] repeat = 60000
23 Aug 09:50:18 - [info] [inject:acf57d63.530a8] crontab = 00 06 \* \* 1,2,3,4,5
23 Aug 09:50:19 - [info] [inject:4c313d7.fb3cec4] crontab = 00 08 \* \* 6,0
23 Aug 09:50:20 - [info] [inject:32a2c77e.cd5d38] crontab = 15 20 \* \* *
23 Aug 09:50:20 - [info] [inject:d7745885.288ba8] repeat = 10800000
23 Aug 09:50:27 - [info] Started flows
23 Aug 09:50:27 - [red] Uncaught Exception:
23 Aug 09:50:27 - Error: ETIMEDOUT
    at null._onTimeout (/home/pi/.node-red/node_modules/node-red-contrib-hue/node_modules/node-hue-api/node_modules/request-util/node_modules/request/request.js:919:15)
    at Timer.listOnTimeout (timers.js:119:15)

Any idea?

**Comment by ghost** [comment]
Im having the same issue (issue #8 ). @fcichos which version of hue hub do you have? also worth checking your flows json file to see if any 'phantom' hue node elements have remained - if so will need to be purged in a text editor as you wont see them in the GUI.

**Comment by MehrCurry** [comment]
Hi,

another one with the same problem:

# Welcome to Node-RED

22 Jan 05:44:46 - [info] Node-RED version: v0.12.5
22 Jan 05:44:46 - [info] Node.js  version: v0.12.6
22 Jan 05:44:46 - [info] Loading palette nodes
22 Jan 05:44:57 - [info] Settings file  : /opt/iobroker/iobroker-data/node-red/settings.js
22 Jan 05:44:57 - [info] User directory : /opt/iobroker/iobroker-data/node-red/
22 Jan 05:44:57 - [info] Flows file : /opt/iobroker/iobroker-data/node-red/flows.json
22 Jan 05:44:57 - [info] Server now running at http://127.0.0.1:1881/
22 Jan 05:44:58 - [info] Starting flows
22 Jan 05:45:05 - [info] [inject:5f47d8b6.a0b828] repeat = 15000
22 Jan 05:45:09 - [info] [inject:1329022c.ecd6fe] repeat = 60000
22 Jan 05:45:16 - [info] [inject:a622cc7a.59dd3] repeat = 300000
22 Jan 05:45:18 - [info] [udp out:MiLight UDP send] udp ready: 192.168.187.46:8899
22 Jan 05:45:19 - [info] [inject:Abfrage Spritpreise] repeat = 600000
22 Jan 05:45:24 - [info] Started flows
22 Jan 05:45:24 - [red] Uncaught Exception:
22 Jan 05:45:24 - Error: ETIMEDOUT
    at null._onTimeout (/opt/iobroker/node_modules/node-red-contrib-hue/node_modules/node-hue-api/node_modules/request-util/node_modules/request/request.js:919:15)
    at Timer.listOnTimeout (timers.js:119:15)

**Comment by ghost** [comment]
Are you using the v2.0 hue hub? (2015/2016 version),or a v1.0? Thanks

**Comment by MehrCurry** [comment]
I am using the old one.

**Comment by urbiworx** [comment]
It is really tough to judge without being able to reproduce the issue here (and the stacktrace does not look helpful either). However it is really likely that the problem occurs when invoking the nupnpSearch method as this is the only method that is called during startup. 

As I am not making network calls on my own and only leverage the node-hue-api I am pretty convinced that it is not a problem within the hue node. It seems to me that node-hue-api is making calls using axios but does not use the ".catch(fn)" mechanism (https://www.npmjs.com/package/axios#handling-errors) to catch and handle timeouts. However I am not completely sure as there does not seem to be a ticket open there. 

Best would be if someone that is affected by this problem tries to invoke the nupnp method directly and see if it happens then also. If yes, please open up a ticket at node-hue-api. Something like:

var hue = require("node-hue-api");
    hue.nupnpSearch(function(err, result) {
        if (err) throw err;
        console.log(JSON.stringify(result));
    });

should be sufficient.

**Comment by MehrCurry** [comment]
I got a step further. When i start node-red with node 0.12.6 i will get the error. With node 4.2.6 running node-red everything seems to be fine.

i tried your little program with both node versions and got
[{"id":"001788fffe1a83c7","ipaddress":"192.168.187.59"}]

**Comment by ghost** [comment]
this resolved itself for me by upgrading from nodejs v4.2.3 to v4.2.6 ! hmmmm.

**Comment by Roaders** [comment]
@sleepingscorpion if you've resolved this yourself perhaps you could close the issue?

**Comment by ghost** [comment]
@Roaders, @fcichos opened the issue...

**Comment by Roaders** [comment]
ah yes, so he did. I saw the last message saying "I resolved this" and thought that you were the original poster. Apologies.
