### ISSUE TITLE
uncaught error crashes node-red

### ISSUE THREAD

**Issue by ghost** [urbiworx/node-red-contrib-hue#8]
Received this initially, when having trouble discovering/registering my 2.0 bridge:

22 Dec 03:03:12 - [info] Starting flows
22 Dec 03:03:19 - [info] Started flows
22 Dec 03:03:56 - [red] Uncaught Exception:
22 Dec 03:03:56 - Error: ETIMEDOUT
    at null._onTimeout (/home/pi/node-red/node_modules/node-red-contrib-hue/node_modules/node-hue-api/node_modules/request-util/node_modules/request/request.js:919:15)
    at Timer.listOnTimeout (timers.js:92:15)

**Comment by bazwilliams** [comment]
I found this when I upgraded nodejs from 0.12 to 4.2.3. I uninstalled both node-red and node-red-contrib-hue and the problem went away after reinstall.

**Comment by bazwilliams** [comment]
Whilst this fixed a different issue, I found after a few minutes I received the same timeout error. Turns out what I had to do was delete the `hue.config` file in my `.node-red` folder and resync my bridge. After a diff I noticed the username had changed.

**Comment by ghost** [comment]
Ok, so for me this seems to have resolved by upgrading to nodejs v4.2.6, no other changes other than that! (of course rebuilt all node modules where applicable)
